import { FundingLead } from './types';
import { calculateScore } from './scoring';

const rawLeads: Omit<FundingLead, 'calculatedScore' | 'rank' | 'scoreBreakdown'>[] = [
    {
        id: '1',
        company: 'Neros',
        domain: 'https://neros.tech',
        linkedin: '',
        amount: 75000000,
        round: 'Series B',
        investors: ['Sequoia Capital', 'Vy Capital US', 'Interlagos'],
        leadInvestor: 'Sequoia Capital',
        country: 'USA',
        dateAnnounced: '2025-11-11',
        hiringTier: 'A',
        techRoles: 23,
        atsProvider: 'Greenhouse',
        careersUrl: 'https://job-boards.greenhouse.io/nerostechnologies',
        sourceUrl: 'https://www.finsmes.com/2025/11/neros-raises-75m-in-series-b-funding.html'
    },
    {
        id: '2',
        company: 'Iambic',
        domain: 'https://iambic.ai',
        linkedin: '',
        amount: 100000000,
        round: 'funding',
        investors: ['Abingworth', 'Alexandria Venture Investments', 'Alumni Ventures', 'ARK', 'Ascenta', 'Catalio', 'Everbright Biofund', 'Freeflow Ventures', 'Illumina Ventures', 'Mubadala', 'Pegasus Tech Ventures', 'Qatar Investment Authority', 'Regeneron Ventures', 'Sequoia', 'Tao Capital Partners', 'Terra Magnum Capital Partners', 'Wilson Sonsini Goodrich & Rosati'],
        leadInvestor: '',
        country: 'United States',
        dateAnnounced: '2025-11-11',
        hiringTier: 'B',
        techRoles: 2,
        atsProvider: 'Internal',
        careersUrl: 'https://iambic.ai/careers',
        sourceUrl: 'https://www.finsmes.com/2025/11/iambic-raises-over-100m-in-funding.html'
    },
    {
        id: '3',
        company: 'AirOps',
        domain: 'https://airops.com',
        linkedin: '',
        amount: 40000000,
        round: 'Series B',
        investors: ['Greylock', 'Unusual Ventures', 'Wing Venture Capital', 'XFund', 'Village Global VC', 'Frontline VC'],
        leadInvestor: 'Greylock',
        country: 'USA',
        dateAnnounced: '2025-11-11',
        hiringTier: 'C',
        techRoles: 0,
        atsProvider: 'Ashby',
        careersUrl: 'https://jobs.ashbyhq.com/airops',
        sourceUrl: 'https://www.finsmes.com/2025/11/airops-raises-40m-in-series-b-funding.html'
    },
    {
        id: '4',
        company: 'Majestic Labs',
        domain: 'https://majestic-labs.ai',
        linkedin: '',
        amount: 100000000,
        round: 'Series A',
        investors: ['Bow Wave Capital', 'Lux Capital', 'SBI', 'Upfront', 'Grove Ventures', 'Hetz Ventures', 'QP Ventures', 'Aidenlair Global', 'TAL Ventures'],
        leadInvestor: 'Bow Wave Capital',
        country: 'Israel',
        dateAnnounced: '2025-11-11',
        hiringTier: 'C',
        techRoles: 0,
        atsProvider: '',
        careersUrl: '',
        sourceUrl: 'https://www.finsmes.com/2025/11/majestic-labs-raises-100m-in-funding.html'
    },
    {
        id: '5',
        company: 'Gamma',
        domain: 'https://gamma.app',
        linkedin: '',
        amount: 68000000,
        round: 'Series B',
        investors: ['Andreessen Horowitz', 'Accel', 'Uncork Capital'],
        leadInvestor: 'Andreessen Horowitz',
        country: 'United States',
        dateAnnounced: '2025-11-11',
        hiringTier: 'C',
        techRoles: 0,
        atsProvider: '',
        careersUrl: '',
        sourceUrl: 'https://www.finsmes.com/2025/11/gamma-raises-68m-in-series-b-funding-at-2-1-billion-valuation.html'
    },
    {
        id: '6',
        company: 'CoLab',
        domain: 'https://colabsoftware.com',
        linkedin: '',
        amount: 72000000,
        round: 'Series C',
        investors: ['Intrepid Growth Partners', 'Insight Partners', 'Y Combinator', 'Pelorus VC', 'Killick Capital', 'Spider Capital'],
        leadInvestor: 'Intrepid Growth Partners',
        country: 'Canada',
        dateAnnounced: '2025-11-11',
        hiringTier: 'B',
        techRoles: 8,
        atsProvider: 'Internal',
        careersUrl: 'https://colabsoftware.com/careers',
        sourceUrl: 'https://www.finsmes.com/2025/11/colab-raises-72m-usd-in-series-c-funding.html'
    },
    {
        id: '7',
        company: 'BITE Data',
        domain: 'https://bitedata.io',
        linkedin: '',
        amount: 2500000,
        round: 'Seed funding',
        investors: ['Las Olas Venture Capital'],
        leadInvestor: 'Las Olas Venture Capital',
        country: 'United States',
        dateAnnounced: '2025-11-11',
        hiringTier: 'C',
        techRoles: 0,
        atsProvider: '',
        careersUrl: '',
        sourceUrl: 'https://www.finsmes.com/2025/11/bite-data-raises-2-5m-in-seed-funding.html'
    },
    {
        id: '8',
        company: 'Spectral Compute',
        domain: 'https://spectralcompute.com',
        linkedin: '',
        amount: 6000000,
        round: 'Seed',
        investors: ['Costanoa', 'Crucible'],
        leadInvestor: 'Costanoa',
        country: 'UK',
        dateAnnounced: '2025-11-10',
        hiringTier: 'C',
        techRoles: 0,
        atsProvider: '',
        careersUrl: '',
        sourceUrl: 'https://www.finsmes.com/2025/11/spectral-compute-raises-6m-in-seed-funding.html'
    },
    {
        id: '9',
        company: 'Cassidy Bio',
        domain: 'https://cassidybio.com',
        linkedin: '',
        amount: 8000000,
        round: 'Seed funding',
        investors: ['Ahren Innovation Capital', 'Lool Ventures', '10D VC', 'AION Lab\'s venture seeding track from AstraZeneca', 'AION Lab\'s venture seeding track from Merck KGaA'],
        leadInvestor: 'Ahren Innovation Capital',
        country: 'Israel',
        dateAnnounced: '2025-11-21',
        hiringTier: 'C',
        techRoles: 0,
        atsProvider: '',
        careersUrl: '',
        sourceUrl: 'https://www.finsmes.com/2025/11/cassidy-bio-closes-8m-in-seed-funding.html'
    },
    {
        id: '10',
        company: 'QSimulate',
        domain: 'https://qsimulate.com',
        linkedin: '',
        amount: 11000000,
        round: 'Seed funding',
        investors: ['Embark Ventures'],
        leadInvestor: 'Embark Ventures',
        country: 'USA',
        dateAnnounced: '2025-11-21',
        hiringTier: 'C',
        techRoles: 0,
        atsProvider: 'Internal',
        careersUrl: 'https://qsimulate.com/careers',
        sourceUrl: 'https://www.finsmes.com/2025/11/qsimulate-raises-11m-in-total-funding.html'
    },
    {
        id: '11',
        company: 'Tailor',
        domain: 'https://tailor.tech',
        linkedin: '',
        amount: 37000000,
        round: 'Series A',
        investors: ['i-nest capital', 'ALPHA', 'Fukoku CVC Fund', 'JPS Growth Investment Limited Partnership (Japan Post Investment Corporation)', 'Sumitomo Mitsui Trust Bank', 'Global Brain', 'Globis Capital Partners', 'New Enterprise Associates (NEA)', 'Y Combinator', 'Japanese private and government-backed funds'],
        leadInvestor: '',
        country: 'USA',
        dateAnnounced: '2025-11-21',
        hiringTier: 'B',
        techRoles: 5,
        atsProvider: 'Internal',
        careersUrl: 'https://www.ycombinator.com/companies/tailor/jobs',
        sourceUrl: 'https://www.finsmes.com/2025/11/tailor-closes-series-a-funding.html'
    },
    {
        id: '12',
        company: 'Twenty',
        domain: 'https://twenty.io',
        linkedin: '',
        amount: 0,
        round: 'Series A',
        investors: ['Caffeinated Capital', 'General Catalyst', 'In-Q-Tel'],
        leadInvestor: 'Caffeinated Capital',
        country: 'USA',
        dateAnnounced: '2025-11-21',
        hiringTier: 'B',
        techRoles: 13,
        atsProvider: 'Internal',
        careersUrl: 'https://twenty.io/careers/',
        sourceUrl: 'https://www.finsmes.com/2025/11/twenty-closes-series-a-funding.html'
    },
    {
        id: '13',
        company: 'Point One Navigation',
        domain: 'https://pointonenav.com',
        linkedin: '',
        amount: 35000000,
        round: 'Series C',
        investors: ['Khosla Ventures', 'IA Ventures', 'UP Partners', 'Alumni Ventures'],
        leadInvestor: 'Khosla Ventures',
        country: 'United States',
        dateAnnounced: '2025-11-21',
        hiringTier: 'C',
        techRoles: 0,
        atsProvider: 'Ashby',
        careersUrl: 'https://jobs.ashbyhq.com/point-one-navigation',
        sourceUrl: 'https://www.finsmes.com/2025/11/point-one-navigation-raises-35m-in-series-c-funding.html'
    },
    {
        id: '14',
        company: 'Genspark',
        domain: 'https://genspark.ai',
        linkedin: '',
        amount: 275000000,
        round: 'Series B',
        investors: ['Lanchi Ventures', 'Emergence Capital Partners', 'SBI Investment', 'LG Technology Ventures', 'Pavilion Capital', 'Uphonest Capital'],
        leadInvestor: 'Lanchi Ventures',
        country: 'USA',
        dateAnnounced: '2025-11-21',
        hiringTier: 'C',
        techRoles: 0,
        atsProvider: '',
        careersUrl: '',
        sourceUrl: 'https://www.finsmes.com/2025/11/genspark-raises-275m-series-b-at-1-25-billion-valuation.html'
    },
    {
        id: '15',
        company: 'Redrob',
        domain: 'https://redrob.io',
        linkedin: '',
        amount: 10000000,
        round: 'Series A',
        investors: ['Korea Investment Partners', 'KB Investment', 'Kiwoom Investment', 'Korea Development Bank Capital', 'Daekyo Investment', 'DS & Partners'],
        leadInvestor: 'Korea Investment Partners',
        country: 'USA',
        dateAnnounced: '2025-11-21',
        hiringTier: 'C',
        techRoles: 0,
        atsProvider: '',
        careersUrl: '',
        sourceUrl: 'https://www.finsmes.com/2025/11/redrob-raises-10m-in-series-a-funding.html'
    },
    {
        id: '16',
        company: 'Perelel',
        domain: 'https://perelelhealth.com',
        linkedin: '',
        amount: 27000000,
        round: 'Growth Funding',
        investors: ['Prelude Growth Partners', 'Unilever Ventures', 'Willow Growth Partners', 'Selva Ventures'],
        leadInvestor: 'Prelude Growth Partners',
        country: 'United States',
        dateAnnounced: '2025-11-20',
        hiringTier: 'C',
        techRoles: 0,
        atsProvider: '',
        careersUrl: '',
        sourceUrl: 'https://www.finsmes.com/2025/11/perelel-raises-27m-in-growth-funding.html'
    },
    {
        id: '17',
        company: 'Cavela AI',
        domain: 'https://cavela.com',
        linkedin: '',
        amount: 6600000,
        round: '',
        investors: ['Susa Ventures', 'XYZ Venture Capital', 'Crossover Ventures', 'Go Global Ventures', 'Propel Venture Partners'],
        leadInvestor: '',
        country: 'USA',
        dateAnnounced: '2025-11-20',
        hiringTier: 'C',
        techRoles: 0,
        atsProvider: '',
        careersUrl: '',
        sourceUrl: 'https://www.finsmes.com/2025/11/cavela-ai-raises-6-6m-in-funding.html'
    },
    {
        id: '18',
        company: 'NestAI',
        domain: 'https://nestai.com',
        linkedin: '',
        amount: 110000000,
        round: '',
        investors: ['Nokia', 'Finnish Industry Investment Ltd (Tesi)', 'PostScriptum'],
        leadInvestor: '',
        country: 'Finland',
        dateAnnounced: '2025-11-20',
        hiringTier: 'C',
        techRoles: 0,
        atsProvider: '',
        careersUrl: '',
        sourceUrl: 'https://www.finsmes.com/2025/11/nestai-raises-e100m-in-funding.html'
    },
    {
        id: '19',
        company: 'Voio',
        domain: 'https://voio.com',
        linkedin: '',
        amount: 8600000,
        round: 'Seed funding',
        investors: ['Laude Ventures', 'The House Fund'],
        leadInvestor: 'Laude Ventures',
        country: 'USA',
        dateAnnounced: '2025-11-20',
        hiringTier: 'B',
        techRoles: 14,
        atsProvider: 'Internal',
        careersUrl: 'https://voio.com/careers',
        sourceUrl: 'https://www.finsmes.com/2025/11/voio-raises-8-6m-in-seed-funding.html'
    },
    {
        id: '20',
        company: 'Kraken',
        domain: 'https://kraken.com',
        linkedin: '',
        amount: 800000000,
        round: 'Funding',
        investors: ['Jane Street', 'DRW Venture Capital', 'HSG', 'Oppenheimer Alternative Investment Management', 'Tribe Capital', 'Arjun Sethi\'s family office', 'Citadel Securities'],
        leadInvestor: '',
        country: 'United States',
        dateAnnounced: '2025-11-20',
        hiringTier: 'C',
        techRoles: 0,
        atsProvider: '',
        careersUrl: '',
        sourceUrl: 'https://www.finsmes.com/2025/11/kraken-raises-800m-in-funding.html'
    },
    {
        id: '21',
        company: 'Wispr',
        domain: 'https://wisprflow.ai',
        linkedin: '',
        amount: 25000000,
        round: 'Series A extension',
        investors: ['Notable Capital', 'Flight Fund'],
        leadInvestor: 'Notable Capital',
        country: 'USA',
        dateAnnounced: '2025-11-20',
        hiringTier: 'B',
        techRoles: 2,
        atsProvider: 'Internal',
        careersUrl: 'https://wisprflow.ai/careers',
        sourceUrl: 'https://www.finsmes.com/2025/11/wispr-raises-25m-in-series-a-extension.html'
    },
    {
        id: '22',
        company: 'Secure.com',
        domain: 'https://secure.com',
        linkedin: '',
        amount: 4500000,
        round: 'first funding',
        investors: ['Disrupt.com'],
        leadInvestor: 'Disrupt.com',
        country: 'UAE',
        dateAnnounced: '2025-11-20',
        hiringTier: 'C',
        techRoles: 0,
        atsProvider: '',
        careersUrl: '',
        sourceUrl: 'https://www.finsmes.com/2025/11/secure-com-raises-usd4-5m-in-first-funding.html'
    },
    {
        id: '23',
        company: 'Norm Ai',
        domain: 'https://norm.ai',
        linkedin: '',
        amount: 50000000,
        round: '',
        investors: ['Blackstone', 'Blackstone Innovations Investments', 'funds affiliated with Blackstone Growth'],
        leadInvestor: 'Blackstone',
        country: 'USA',
        dateAnnounced: '2025-11-20',
        hiringTier: 'B',
        techRoles: 5,
        atsProvider: 'Internal',
        careersUrl: 'https://norm.ai/careers/',
        sourceUrl: 'https://www.finsmes.com/2025/11/norm-ai-raises-50m-in-funding.html'
    },
    {
        id: '24',
        company: 'Stuut Technologies',
        domain: 'https://stout.ai',
        linkedin: '',
        amount: 29500000,
        round: 'Series A',
        investors: ['Andreessen Horowitz', 'Activant Capital', 'Khosla Ventures', '1984.vc', 'Page One Ventures', 'Vesey Ventures', 'Carya Venture Partners', 'Valley Ventures'],
        leadInvestor: 'Andreessen Horowitz',
        country: 'USA',
        dateAnnounced: '2025-11-20',
        hiringTier: 'C',
        techRoles: 0,
        atsProvider: '',
        careersUrl: '',
        sourceUrl: 'https://www.finsmes.com/2025/11/stuut-technologies-raises-29-5m-in-series-a-funding.html'
    }
];

export const MOCK_LEADS: FundingLead[] = rawLeads.map(calculateScore).sort((a, b) => b.calculatedScore - a.calculatedScore);
